### ISSUE TITLE
Maven Central Only Offers 1.0

### ISSUE THREAD

**Issue by wlfbck** [Billy-Bichon/liveGQL#3]
Title basically says it all, maven central only offers version 1.0 but not 1.1 :) Would be great if you could make it available there.

**Comment by wlfbck** [comment]
@billybichon ? :)

**Comment by billybichon** [comment]
Hi @wlfbck,

Thanks for the alert.
So sorry for the time it took I had other matters to attend to, it should be fine by now :)

**Comment by wlfbck** [comment]
All good, thank you very much!
